import Head from "next/head";
import { useEffect, useState } from "react";
import JobList from "@/components/JobList";
import { supabase } from "../config/supabaseClient";
import { Job, JobItem } from "@/config/types";

export default function Home() {
  const [jobs, setJobs] = useState<any>([]);
  const [err, setErr] = useState<boolean>(false);

  useEffect(() => {
    // Fetch the stored data from the supabase table scraper
    async function fetchJobs() {
      const { data, error } = await supabase
        .from("scraper")
        .select()
        .order("created_at", { ascending: false });
        
      if (error !== null) {
        setErr(true);
      }
      setJobs(data);
    }

    fetchJobs();
  }, []);

  return (
    <div className="bg-slate-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-3xl px-4 m-auto">
        <div className="flex flex-col items-center justify-center w-full min-h-screen py-3 align-center">
          {!err && jobs?.length === 0 ? (
            <p className="text-lg font-medium">⚠️ No job found</p>
          ) : err ? (
            <p className="text-lg font-medium">⁉️ An error occured</p>
          ) : (
            jobs?.map((item: Job) =>
              item.jobs.map((el: JobItem) => (
                <JobList
                  key={el.link}
                  title={el.title}
                  company={el.company}
                  location={el.location}
                  link={el.link}
                />
              ))
            )
          )}
        </div>
      </main>
    </div>
  );
}
